const state = {
  xp:Number(localStorage.getItem('iq-xp')||0), streak:Number(localStorage.getItem('iq-streak')||0),
  completed:JSON.parse(localStorage.getItem('iq-completed')||'[]'), mistakes:JSON.parse(localStorage.getItem('iq-mistakes')||'[]'),
  sound:localStorage.getItem('iq-sound')!=='off', quiz:null
};

const app=document.querySelector('#app'), toast=document.querySelector('#toast');
function save(){localStorage.setItem('iq-xp',state.xp);localStorage.setItem('iq-streak',state.streak);localStorage.setItem('iq-completed',JSON.stringify(state.completed));localStorage.setItem('iq-mistakes',JSON.stringify([...new Set(state.mistakes)]));localStorage.setItem('iq-sound',state.sound?'on':'off');updateTop()}
function updateTop(){document.querySelector('#xpValue').textContent=state.xp;document.querySelector('#streakValue').textContent=state.streak;document.querySelector('#soundButton').textContent=state.sound?'🔊':'🔇'}
function beep(ok=true){if(!state.sound)return;const A=new (window.AudioContext||window.webkitAudioContext)(),o=A.createOscillator(),g=A.createGain();o.connect(g);g.connect(A.destination);o.frequency.value=ok?660:180;g.gain.setValueAtTime(.06,A.currentTime);g.gain.exponentialRampToValueAtTime(.001,A.currentTime+.18);o.start();o.stop(A.currentTime+.18)}
function notify(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function confetti(){const box=document.querySelector('#confetti');box.innerHTML='';for(let i=0;i<70;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.background=['#22d3ee','#37e89b','#ffd54a','#ff6fb5','#a78bfa'][i%5];p.style.animationDelay=Math.random()*.5+'s';box.appendChild(p)}setTimeout(()=>box.innerHTML='',2400)}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5)}
function setView(html){app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'});updateTop()}

function home(){
  const tpl=document.querySelector('#homeTemplate').content.cloneNode(true);app.innerHTML='';app.append(tpl);
  const grid=document.querySelector('#missionGrid');
  missions.forEach(m=>{const done=state.completed.includes(m.id);const card=document.createElement('button');card.className='mission-card';card.style.setProperty('--accent',m.accent);card.dataset.mission=m.id;card.innerHTML=`<span class="mission-number">MUNDO ${m.number}</span><div class="mission-emoji">${m.emoji}</div><h3>${m.title}</h3><p>${m.description}</p><div class="mission-foot"><span>${questions.filter(q=>q.cat===m.id).length} retos</span><span class="${done?'done':''}">${done?'✓ Dominado':'Jugar →'}</span></div>`;grid.append(card)});
  const progress=Math.round(state.completed.length/missions.length*100);document.querySelector('#homeProgressBar').style.width=progress+'%';document.querySelector('#homeProgressText').textContent=progress+'%';document.querySelector('#mistakeCount').textContent=state.mistakes.length;updateTop();
}

function visual(type){
  if(type==='pc')return `<div class="pc-parts"><div class="part"><b>🖥️</b>Monitor</div><div class="part"><b>🧠</b>CPU</div><div class="part"><b>⌨️</b>Teclado</div><div class="part"><b>🖱️</b>Mouse</div><div class="part"><b>🖨️</b>Impresora</div></div>`;
  if(type==='cards')return `<div class="pc-parts"><div class="part"><b>🔩</b>Hardware<br><small>Se toca</small></div><div class="part"><b>✨</b>Software<br><small>Programas</small></div></div>`;
  if(type==='mouse')return `<div style="text-align:center"><div style="font-size:110px">🖱️</div><b>Izquierdo · Rueda · Derecho</b><p style="color:#aeb8d8">La rueda permite desplazarse ↕</p></div>`;
  if(type==='window')return `<div class="window-demo"><div class="window-bar"><b>Mi carpeta</b><div class="window-controls"><span class="window-control">—</span><span class="window-control">□</span><span class="window-control">✕</span></div></div><div class="window-body">📁 Ventana de práctica</div></div>`;
  return `<div class="keyboard-demo"><span class="key wide">CTRL</span><span class="key">C</span><span class="key">V</span><span class="key">X</span><span class="key">Z</span><span class="key wide">⊞ WIN</span><span class="key">E</span><span class="key">R</span><span class="key">L</span><span class="key">D</span></div>`;
}

function lesson(id){const m=missions.find(x=>x.id===id);setView(`<section class="screen"><div class="screen-head"><button class="back" data-action="home">← Inicio</button><div class="screen-title"><span class="eyebrow">MUNDO ${m.number}</span><h1>${m.emoji} ${m.title}</h1><p>${m.description}</p></div><span></span></div><div class="lesson-layout"><aside class="lesson-sidebar panel"><div class="lesson-icon">${m.emoji}</div><div class="fact-list">${m.facts.map(([a,b])=>`<div class="fact"><strong>${a}</strong><br>${b}</div>`).join('')}</div></aside><article class="lesson-content panel"><span class="eyebrow">LABORATORIO VISUAL</span><h2>Míralo, dilo y recuérdalo</h2><p>Explícalo con tus propias palabras. Si puedes enseñárselo a otra persona, ya lo aprendiste.</p><div class="visual-lab">${visual(m.visual)}</div><div class="lesson-actions"><button class="primary" data-start-mission="${m.id}">🎮 Comenzar reto</button><button class="secondary" data-action="flash">🧠 Repaso rápido</button></div></article></div></section>`)}

function startQuiz(pool,mode='mission',label='Reto'){state.quiz={items:shuffle(pool),index:0,score:0,lives:3,mode,label,answered:false,wrongCats:{}};renderQuestion()}
function renderQuestion(){const qz=state.quiz,q=qz.items[qz.index],pct=Math.round(qz.index/qz.items.length*100);setView(`<section class="screen"><div class="screen-head"><button class="back" data-action="home">✕ Salir</button><div class="screen-title"><span class="eyebrow">${qz.label}</span><h1>${qz.mode==='exam'?'Jefe Final':'Reto de aprendizaje'}</h1></div><span class="lives">${qz.mode==='learn'?'∞':Array(qz.lives).fill('❤️').join('')}</span></div><div class="quiz-shell panel"><div class="quiz-top"><div><div class="quiz-count">Pregunta ${qz.index+1} de ${qz.items.length}</div><div class="progress"><i style="width:${pct}%"></i></div></div><strong>${qz.score} pts</strong></div><article class="question-card"><span class="question-tag">${missions.find(m=>m.id===q.cat)?.title||'INFORMÁTICA'}</span><div class="question-visual">${q.v}</div><h2>${q.q}</h2><div class="answers">${q.a.map((a,i)=>`<button class="answer" data-answer="${i}"><b>${String.fromCharCode(65+i)}.</b> ${a}</button>`).join('')}</div><div id="feedback" class="feedback"></div><button id="nextButton" class="primary quiz-next" data-action="next">Siguiente →</button></article></div></section>`)}
function answer(index){const qz=state.quiz;if(qz.answered)return;qz.answered=true;const q=qz.items[qz.index],ok=index===q.c;document.querySelectorAll('.answer').forEach((b,i)=>{b.disabled=true;if(i===q.c)b.classList.add('correct');else if(i===index)b.classList.add('wrong')});const fb=document.querySelector('#feedback');fb.className=`feedback show ${ok?'good':'bad'}`;fb.innerHTML=ok?`<b>✅ ¡Correcto!</b><br>${q.e}`:`<b>🛠️ Casi. La respuesta correcta es: ${q.a[q.c]}</b><br>${q.e}`;document.querySelector('#nextButton').classList.add('show');if(ok){qz.score++;state.xp+=10;state.streak++;beep(true)}else{state.streak=0;qz.lives=Math.max(0,qz.lives-1);state.mistakes.push(q.id);qz.wrongCats[q.cat]=(qz.wrongCats[q.cat]||0)+1;beep(false)}save()}
function next(){const qz=state.quiz;qz.index++;qz.answered=false;if(qz.index>=qz.items.length)return results();renderQuestion()}
function results(){const qz=state.quiz,total=qz.items.length,percent=Math.round(qz.score/total*100),grade=(qz.score/total*10).toFixed(1);if(qz.mode==='mission'){const cat=qz.items[0]?.cat;if(percent>=70&&!state.completed.includes(cat)){state.completed.push(cat);state.xp+=50}}if(percent>=80){confetti();beep(true)}save();const rank=percent===100?'Maestro Supremo 🏆':percent>=80?'Experto Informático ⭐':percent>=60?'Técnico en progreso 🔧':'Aprendiz valiente 🚀';const cats=Object.entries(qz.wrongCats).sort((a,b)=>b[1]-a[1]);setView(`<section class="screen"><div class="results panel"><div class="result-orb" style="--score:${percent*3.6}deg"><strong>${grade}/10</strong></div><span class="eyebrow">MISIÓN COMPLETADA</span><h1>${rank}</h1><p>Acertaste <b>${qz.score} de ${total}</b>. ${percent>=80?'¡Estás muy cerca de dominar el examen!':'Practica únicamente los errores y vuelve a intentarlo.'}</p><div class="mastery-list">${cats.length?cats.map(([c,n])=>`<div class="mastery-row"><span>${missions.find(m=>m.id===c)?.emoji} ${missions.find(m=>m.id===c)?.title}</span><b>${n} por reparar</b></div>`).join(''):'<div class="mastery-row"><span>✨ Ningún tema pendiente</span><b>Perfecto</b></div>'}</div><div class="result-actions"><button class="primary" data-action="mistakes">🛠️ Practicar errores</button><button class="secondary" data-action="exam">Repetir simulacro</button><button class="secondary" data-action="home">Volver al mapa</button></div></div></section>`)}

function flash(){setView(`<section class="screen"><div class="screen-head"><button class="back" data-action="home">← Inicio</button><div class="screen-title"><span class="eyebrow">REPASO DE EMERGENCIA</span><h1>🧠 Lo esencial en 10 minutos</h1><p>Lee cada tarjeta en voz alta, tápala y trata de repetirla sin mirar.</p></div><span></span></div><div class="flash-grid">${flashCards.map(([a,b])=>`<article class="flash-card"><strong>${a}</strong><span>${b}</span></article>`).join('')}</div><div class="result-actions"><button class="primary" data-action="turbo">⚡ Probar ruta turbo</button><button class="secondary" data-action="exam">🏆 Ir al simulacro</button></div></section>`)}
function mistakes(){const pool=questions.filter(q=>state.mistakes.includes(q.id));if(!pool.length){setView(`<section class="panel empty-state"><b>✨</b><h1>No hay errores guardados</h1><p>Juega una misión o el simulacro. Aquí aparecerán las preguntas que necesites reforzar.</p><button class="primary" data-action="exam">Ir al simulacro</button></section>`);return}startQuiz(pool,'learn','TALLER DE REPARACIÓN')}
function turbo(){const essentials=['q1','q2','q3','q7','q8','q9','q10','q12','q13','q14','q15','q18','q19','q20','q21','q22','q24','q25','q26','q27','q28','q29','q30','q31','q34'];startQuiz(questions.filter(q=>essentials.includes(q.id)),'learn','RUTA TURBO · 25 MIN')}
function exam(){startQuiz(shuffle(questions).slice(0,25),'exam','SIMULACRO DE EXAMEN')}

app.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.mission)return lesson(el.dataset.mission);if(el.dataset.startMission){const pool=questions.filter(q=>q.cat===el.dataset.startMission);return startQuiz(pool,'mission',`MUNDO ${missions.find(m=>m.id===el.dataset.startMission).number}`)}if(el.dataset.answer!==undefined)return answer(Number(el.dataset.answer));const action=el.dataset.action;if(action==='home')home();if(action==='turbo')turbo();if(action==='exam')exam();if(action==='mistakes')mistakes();if(action==='flash')flash();if(action==='next')next()});
document.querySelector('#soundButton').addEventListener('click',()=>{state.sound=!state.sound;save();notify(state.sound?'Sonidos activados':'Sonidos desactivados')});
updateTop();home();
